model_params:
  name: "MNISTVanillaVAE"
  in_channels: 1
  latent_dim: 8


data_params:
  data_path: "Data/"
  dataset_name: "MNIST"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 1.0
  kld_weight: 0.00025
  manual_seed: 1265
  backward_option: "torch_jd_mtl_backward"
  kld_preferred_weight: 0.1

trainer_params:
  #gpus: []
  max_epochs: 64

logging_params:
  save_dir: "logs/"
